# server:
#   port: 8080
# spring:
#   application:
#     name: api-gateway
#   cloud:
#     gateway:
#       routes:
#         - id: microservice-one
#           uri: http://localhost:8081
#           predicates:
#             - Path=/api/v1/messages/**
